version: 2.1
orbs:
  snyk: snyk/snyk@0.0.8

jobs:
  build:
    docker:
      - image: circleci/node:12.9.1-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - run: yarn install


      - run: yarn lint

      - run: yarn size

      - run: yarn test

      - run: yarn ci:cypress-run

      - run: yarn build